default:
    image: node:18

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm/

variables:
    NPM_TOKEN: ${GITLAB_PROJECT_TOKEN}
    GITLAB_TOKEN: ${GITLAB_PROJECT_TOKEN}

.npmrc:
    before_script:
        - |
            {
                echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
                echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${GITLAB_PROJECT_TOKEN}"
            } | tee -a .npmrc

.dependencies_cache:
    extends: .npmrc
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - .npm
        policy: pull

stages:
    - install
    - analysis
    - build
    - release

install:
    extends: .dependencies_cache
    stage: install
    script:
        - npm ci --cache .npm --prefer-offline
    cache:
        policy: pull-push
    artifacts:
        expire_in: 1h
        paths:
            - node_modules

lint:
    stage: analysis
    dependencies:
        - install
    script:
        - npm run lint

dependencies-scan:
    stage: analysis
    dependencies:
        - install
    script:
        - npm audit --omit=dev

test:
    stage: analysis
    dependencies:
        - install
    script:
        - npm run test:ci
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        untracked: true
        when: always
        reports:
            junit:
                - junit.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage/cobertura-coverage.xml

build:
    stage: build
    dependencies:
        - install
    artifacts:
        untracked: true
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    script:
        - npm run build

publish:
    extends: .npmrc
    stage: release
    dependencies:
        - install
        - test
        - build
    only:
        - main
    script:
        - npm run docs
        - cp -r docs public
        - npx semantic-release
    artifacts:
        paths:
            - public